# Generated by Django 4.2 on 2024-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                default="148224db6f86ce75de844b5081e92b5a",
                max_length=50,
                verbose_name="Токен",
            ),
            preserve_default=False,
        ),
    ]
