# Generated by Django 5.0.2 on 2024-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default="2024-02-17", verbose_name="Дата производства продукта"
            ),
        ),
    ]
