# Generated by Django 4.2 on 2024-03-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_version"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
